In [1]:
import pandas as pd

In [2]:
import numpy as np
from sklearn.metrics import log_loss, average_precision_score, label_ranking_average_precision_score_score
from sklearn.metrics import coverage_error, f1_score, label_ranking_loss, roc_auc_score, accuracy_score

In [3]:
y_true = np.array([[1, 0, 0], [0, 0, 1]])
y_score = np.array([[0.75, 0.5, 1], [1, 0.2, 0.1]])
coverage_error(y_true, y_score)

2.5

In [17]:
y_true = np.array([[0, 0, 1, 1],
          [0, 0, 1, 0],
          [1, 1, 0, 0],
          [1, 0, 0, 0]])
y_score = np.array([[0.1, 0.2, 0.8, 0.8],  
           [0.9, 0.1, 0.2, 0.4],  
           [0.1, 0.2, 0.8, 0.6], 
           [0.8, 0.4, 0.2, 0.2]])
y_pred = np.array([[0, 0, 1, 1],  
          [1, 0, 0, 0],  
          [0, 0, 1, 1], 
          [1, 0, 0, 1]])

In [18]:
roc_auc_score(y_true, y_score)

0.59375

In [5]:
import utilities

In [ ]:
'accuracy'
'f1_score'
'coverage'
'label_ranking'
'roc_auc_score'
'log_loss'
'average_precision'
'brier_loss'
'hamming_loss'
'precision'
'recall'
'zero_one_loss'
'label_ranking_average_precision'

In [76]:
y_pred

array([[0, 0, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 0]])

In [77]:
np.array(y_pred)

array([[0, 0, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 0]])

In [81]:
multilabel_brier_loss(y_true, y_pred, 'macro')

0.4375

4

In [60]:
mask = y_true[:,2]==1

array([ True,  True, False, False])

In [58]:
y_true[y_true[:,2]==1]

array([[0, 0, 1, 1],
       [0, 0, 1, 0]])

In [45]:
multilabel_brier_loss(y_true, y_pred)

[0.25, 0.25, 0.75, 0.25]

In [46]:
multilabel_brier_loss(y_true, y_score)

[0.032499999999999994, 0.36750000000000005, 0.6125, 0.07]

In [36]:
from sklearn.metrics import brier_score_loss
brier_score_loss([1,1,0,0], [0,0,1,1])

1.0

In [39]:
y_true, y_score(y_true, y_score)

TypeError: 'list' object is not callable

In [21]:
y_true = [[0, 0, 1, 1],
          [0, 0, 1, 0],
          [1, 1, 0, 0],
          [1, 0, 0, 0]]
y_score = [[0.9, 0.4, 0.8, 0.8],  
           [0.9, 0.1, 0.3, 0.4],  
           [0.1, 0.2, 0.8, 0.6], 
           [0.8, 0.4, 0.2, 0.2]] 
coverage_error(y_true, y_score)

2.75

In [ ]:
log loss

In [18]:
probability based metric

2.75

In [66]:
from sklearn.metrics import label_ranking_loss

In [76]:
y_true = [[0, 0, 0, 1],
          [0, 0, 1, 0],
          [1, 1, 0, 0],
    [1, 0, 0, 0]]
y_score = [[0.9, 0.2, 0.1, 0.8], 
 [0.9, 0.1, 0.3, 0.4], 
 [0.1, 0.2, 0.8, 0.6], 
 [0.5, 0.4, 0.4, 0.2]]
label_ranking_loss(y_true, y_score)

0.5